#!/usr/bin/env bash
#
# PreToolUse hook (Bash): blocks `git commit` when AI-attribution lines would
# end up in the commit. The project policy is: clean history, no
# Co-Authored-By: Claude, no claude.ai links, no "Generated by …" footers.
#
# Bare mentions of "claude" or "ai" inside diffed code or docs are *allowed* —
# we only care about commit metadata. So this checks:
#   - the proposed commit message
#   - lines that look like attribution footers in staged content
#
# Exit 2 = blocked; stderr is returned to the agent.
#
set -uo pipefail

cmd=$(jq -r '.tool_input.command // empty')

case "$cmd" in
  *"git commit"*) ;;
  *) exit 0 ;;
esac

# Patterns that should never appear in commit metadata
attribution_pattern='Co-?Authored-?By:.*Claude|Co-?Authored-?By:.*Anthropic|Generated by Claude|Generated with Claude|claude\.ai|🤖.*[Cc]laude'

# Build the inspection target: the command itself (often has `-m "msg"`) plus
# the diff of any newly created files (commit messages are added via -F / -m,
# so scanning $cmd covers HEREDOC-style messages too).
hits=$(
  {
    printf '%s\n' "$cmd"
    git diff --cached 2>/dev/null | grep -E '^\+' | grep -vE '^\+\+\+' || true
  } | grep -nE "$attribution_pattern" || true
)

if [ -n "$hits" ]; then
  {
    echo "Confidentiality check failed — AI-attribution detected in commit:"
    echo "$hits"
    echo
    echo "Remove every Co-Authored-By: Claude, claude.ai link, and 'Generated by …' footer."
    echo "Project policy: clean commit history without AI tooling attribution."
  } >&2
  exit 2
fi

exit 0
